[package]
name = "tcc-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tcc-spec = { workspace = true }
tcc-manifest = { workspace = true }
tcc-capability = { workspace = true }
tcc-ui = { workspace = true }
thiserror = { workspace = true }
tcc-crypto.workspace = true
hex = "0.4.3"

[lints]
workspace = true
